### ISSUE TITLE
Add Rock Band Collection DLC from Archive

### ISSUE THREAD

**Issue by MDashK** [r-Roms/r-Roms.github.io#6]
Hey, how are you?

First off, a big thanks for your resources. Was really helpful for me in finding a few things.

I took the liberty of uploading the following +120GB DLC collection to archive, since it seems it wasn't there.
I was looking for a specific DLC and was only able to find it in this collection.

Maybe add it to the 360 section as well:

https://archive.org/details/rock-band-dlc-complete-collection-xbox-360-by-americo

Thanks!

**Comment by ineedalife15** [comment]
Link has been added.
